### ISSUE TITLE
Where can I downloade the file?

### ISSUE THREAD

**Issue by Trtrtr70** [Magisk-Modules-Alt-Repo/Simple_BootloopSaver#4]

**Comment by Thisisauser6443** [comment]
You'll need to find the green button named `<> Code` (If you're trying to get it from your phone, just force a desktop site, in your browser's settings)

However, there's a small issue - If you were a bit too eager, and don't know the general structure of modules, you might try flashing `Simple_BootloopSaver-master.zip` file, only to get an `! Unzip error` printout. It's because of how repository files, on GitHub, are archived, before you actually start downloading them. To fix that up, you'll need to:

1. Extract all of the files from that archive you just downloaded
2. Travel down the new directories, until you get to a folder that contains stuff like `module.prop`, `service.sh`... etc.
3. Put all of those files into a `ZIP` archive.
4. Flash that archive in Magisk

_And that **should** be it :)_

**Comment by Trtrtr70** [comment]
Thank you kind ser.

**Comment by SalvatoreNoschese** [comment]
I repacked
[Simple_BootloopSaver-fix.zip](https://github.com/Magisk-Modules-Alt-Repo/Simple_BootloopSaver/files/14202321/Simple_BootloopSaver-fix.zip)
